typography_spectrum: 0
color:
  brandColors:
    - '#fdfdfd'
    - '#0a0b0d'
    - '#a46d58'
    - '#3a7b91'
    - '#333740'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9005685991141945
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Timur Shakuov
  email: t.shakuov@gmail.com
name: mockertim
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
