typography_spectrum: 0
color:
  brandColors:
    - '#fdfdfd'
    - '#0a0b0d'
    - '#a46d58'
    - '#3a7b91'
    - '#333740'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9005685991141945
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Timur Shakuov
  email: t.shakuov@gmail.com
name: mockertim
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Just For Fun
    id: f564014e-489c-4e63-9deb-80e2b59e02cb
    type: content
favicon: null
title: MockerTim's Site
description: Winter moments
purpose: []
